#!/bin/bash

# Script to get passwords in Sway

SALT=$(wofi --dmenu --lines 1 2>/dev/null)
MASTER=$(wofi --dmenu --password --lines 1 2>/dev/null)

PASSW=$(printf "%s\n%s\n" "$SALT" "$MASTER" | slpg)

if [ -n "$PASSW" ]; then
	wtype "$PASSW"
fi
